### ISSUE TITLE
Any plans for an API integration?

### ISSUE THREAD

**Issue by Inkybro** [otwcode/otwarchive#1863]
Hello,

Came across this repo today, as well as AO3. Looks cool. Curious if there is an API implemented or if this is planned in any way. Either way, is that something that may be accepted into the official if I were to implement it myself?

Thank you for your time!

**Comment by scottsds** [comment]
Hi @Inkybro! 

Sorry for taking so long to get back to you! 

An API is something that we plan to implement in future, and can be seen on our [Public Roadmap] (http://archiveofourown.org/admin_posts/295) under version 1.0. 

While we do accept Pull requests from non-Staff coders, they're typically of a smaller and less in-depth nature. Something as large as an API implementation would be best served when it comes from within our development team. 

We're currently working in-house on a smaller API implementation that would allow our [OpenDoors team] (http://opendoors.transformativeworks.org/) to import at-risk archives more quickly. You can see the proposed work by checking the [Importing Milestone] (https://github.com/otwcode/otwarchive/pulls?q=is%3Aopen+is%3Apr+milestone%3A%220.9.53%3A+Importing%22).

Hopefully that answers your questions!

**Comment by chaosagent** [comment]
Hello,

Is there any particular reason that the web frontend wasn't built on a separate backend API layer from the start? An application structure like that would seem to be a lot more manageable than the backend and frontend mashed together with a public api sticking out the side...

**Comment by ariana-paris** [comment]
Hello again @chaosagent 

There are a few reasons why the web front-end is in the same application as the server-side code. Archive of our Own was originally designed to be a web site only. When the project was started in 2008, mobile devices were few and far between and there seemed little need to cater for machine-to-machine communications in a fan fiction archive. It was built on Rails' standard MVC architecture with a view to facilitating ease of development for new coders, with everything in the same project. Over the years, the underlying API has evolved to serve the needs of the web site as it became more complex to cater to more users.

This also explains why we can't just open up the existing Rails controllers to JSON requests; their current responses aren't suitable for general consumption. Rewriting several years' worth of web view-specific code would be prohibitively time-consuming for a small group of volunteers. This leaves us with only one option: gradually bolt on an API sticking out the side, as you put it. :)

Hope that clears things up!

Ariana
(Archive developer)
