### ISSUE TITLE
ePub Cover Art

### ISSUE THREAD

**Issue by moberemk** [otwcode/otwarchive#2047]
So here's the thing: I have a lot of books in my collection, and they're only identified thanks to cover art...which isn't exactly useful when cover art isn't available. Any chance of getting some sort of basic cover art for downloaded ePub files? It would make library management in Google Play books and similar programs a whole lot easier.

**Comment by scottsds** [comment]
Hi @moberemk! Thanks for the feature request. I've added it to our Public-facing trello which already contained a request for this feature. You can see it here: https://trello.com/c/tGZGrUur/422-ability-to-upload-an-image-as-cover-header-for-a-work .
