### ISSUE TITLE
vagrant: Failed connect to devdebrepo.ao3.org:80; Connection refused

### ISSUE THREAD

**Issue by novalis** [otwcode/otwarchive#2101]
Following these instrucitons: https://github.com/otwcode/otwarchive/wiki/Development-Environment#First_run

Using vagrant 1.5.0 on Ubuntu 14.04.

$ vagrant init aooo/archive_of_our_own  A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'aooo/archive_of_our_own'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'aooo/archive_of_our_own' is up to date...
==> default: Setting the name of the VM: otwarchive-dev_default_1430888314580_16436
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8081 => 8081 (adapter 1)
    default: 9200 => 8082 (adapter 1)
    default: 3606 => 8083 (adapter 1)
    default: 1025 => 8084 (adapter 1)
    default: 7000 => 8085 (adapter 1)
    default: 7001 => 8086 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/novalis/otwarchive-dev
==> default: Running provisioner: shell...
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed connect to devdebrepo.ao3.org:80; Connection refused

**Comment by Scripore** [comment]
Hey @novalis, the box name has been changed, the command is now `vagrant init aooo/ao3_1`

**Comment by novalis** [comment]
Thanks!  Looks like the docs have been updated too, so I'm going to close this; I'll open a new ticket if I run into any more trouble.
