### ISSUE TITLE
Vagrant development box is out of date

### ISSUE THREAD

**Issue by chaosagent** [otwcode/otwarchive#2152]
The Vagrant box linked to in the wiki (aooo/ao3_1) only has rails 1.9.something (while this app requires 2.0.0), and aooo/archive_of_our_own cannot be downloaded.

**Comment by ariana-paris** [comment]
Hello,

Thanks for your interest in our project and for getting in touch! We do have plans to update the Vagrant image, but probably not until after the summer holidays as we're a bit stretched volunteer-wise right now and other priorities unfortunately have to take precedence. But we'll definitely update the Wiki when a new box is available.

Cheers,

Ariana

**Comment by scottsds** [comment]
Hi @chaosagent! 

Try running the following bash script, it should set you up with the correct version of Ruby:
```
#!/bin/bash
if [ "$1" != "force" ] 
 then

cat <<EOT

This script resets the rvm enviroment, downloading and reinstalling 
ruby and the gems to a known good state.

EOT
 read -p "Are you sure? " -n 1
 if [[ ! $REPLY =~ ^[Yy]$ ]]
 then
    echo
    exit 1
 fi
fi

if [ -d ~/.rvm ] ; then
  mv ~/.rvm ~/.rvm-`date +%F-%H-%M-%N`
fi

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -L https://get.rvm.io | bash -s stable
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

rvm autolibs read-fail
rvm install ruby-2.0.0-p643
rvm --default use 2.0.0-p643
rvm gemset use global 
gem install rvm-capistrano
gem install bundler
gem install god
gem install unicorn
rvm rvmrc warning ignore /home/ao3app/app/current/Gemfile
```

This should fix your VM until we have a chance to publish a new VM Image!

**Comment by chaosagent** [comment]
Thanks :)
