### ISSUE TITLE
Bug tracking link in README.md

### ISSUE THREAD

**Issue by noellee** [otwcode/otwarchive#2165]
Should the link be changed to the Github issue tracker instead of the Google Code tracker, now that Google Code projects are read-only?

**Comment by ariana-paris** [comment]
Good catch - we haven't changed the readme in ages and didn't spot that it had a link to Google Code.

In fact, our development issues have actually moved to [Jira](https://otwarchive.atlassian.net/projects/AO3/issues). I'll log an issue there so we'll change the readme.

Thanks!

**Comment by ariana-paris** [comment]
Logged as https://otwarchive.atlassian.net/browse/AO3-4334
