### ISSUE TITLE
Issue: Documentation

### ISSUE THREAD

**Issue by walterhpdx** [otwcode/otwarchive#2258]
Is there any way to get a definitive, "This is how you need to install on OS X" or Linux?  Because I've watched the documentation change over the last year with each abortive attempt I've made at installing otwarchive on my own machine, and it keeps getting sparser and less informative.

I could possibly write it myself, but each time I try and install, there's something new missing.  I've never gotten the software up and running successfully, nor have I gotten the database to populate with skeleton data.  I need to move my largest archive away from eFiction, and otwarchive is the logical - but most difficult - choice.

**Comment by sarken** [comment]
Hi, Walter!

Thanks for your interest in using the otwarchive software! I should note that all of our documentation is geared toward setting up the otwarchive software for development purposes only, and we don't currently recommend (and can't offer support for) running otwarchive on a production site. While our original intention was to offer a software package that would allow fans to easily set up their own archives, the growth of the Archive of Our Own means otwarchive has essentially become enterprise software designed to run on a fairly complex setup of dedicated servers.

That said, even for folks using the same OS, the process of installing otwarchive will be a little different depending on your exact setup, so we recommend using Vagrant instead: https://github.com/otwcode/otwarchive/wiki/Development-Environment 

However, a few of us are developing locally on OS X and have used the instructions at https://github.com/otwcode/otwarchive/wiki/OS-X-setup in the past, so if you'd like to reply here with which steps are unclear and what error messages you're getting, we should be able to help. We don't have any Linux developers at the moment, so those instructions are unfortunately out of date. If you do install on Linux and want to update the instructions, we would be very grateful!

Finally, a heads-up: we're planning a major upgrade of Elasticsearch and our searching and filtering code at the start of the year, which will probably change the set up process and require changes to any existing installations.


Sarken
AO3 Development Committee Co-chair
